###  Index partagé par toutes les colonnes

In [2]:
import pandas as pd
fandango = pd.read_csv("C:/Users/abdou/training_dataS/Data/fandango_score_comparison.csv")

In [3]:
fandango.head(2)

,FILM,RottenTomatoes,RottenTomatoes_User,Metacritic,Metacritic_User,IMDB,Fandango_Stars,Fandango_Ratingvalue,RT_norm,RT_user_norm,...,IMDB_norm,RT_norm_round,RT_user_norm_round,Metacritic_norm_round,Metacritic_user_norm_round,IMDB_norm_round,Metacritic_user_vote_count,IMDB_user_vote_count,Fandango_votes,Fandango_Difference
0,Avengers: Age of Ultron (2015),74,86,66,7.1,7.8,5.0,4.5,3.70,4.3,...,3.90,3.5,4.5,3.5,3.5,4.0,1330,271107,14846,0.5
1,Cinderella (2015),85,80,67,7.5,7.1,5.0,4.5,4.25,4.0,...,3.55,4.5,4.0,3.5,4.0,3.5,249,65709,12640,0.5

In [4]:
fandango.index

RangeIndex(start=0, stop=146, step=1)

In [5]:
fandango.shape

(146, 22)

### Utiliser des index entier pour sélectionner des lignes

In [7]:
fandango[140:]

,FILM,RottenTomatoes,RottenTomatoes_User,Metacritic,Metacritic_User,IMDB,Fandango_Stars,Fandango_Ratingvalue,RT_norm,RT_user_norm,...,IMDB_norm,RT_norm_round,RT_user_norm_round,Metacritic_norm_round,Metacritic_user_norm_round,IMDB_norm_round,Metacritic_user_vote_count,IMDB_user_vote_count,Fandango_votes,Fandango_Difference
140,Inside Out (2015),98,90,94,8.9,8.6,4.5,4.5,4.90,4.50,...,4.30,5.0,4.5,4.5,4.5,4.5,807,96252,15749,0.0
141,Mr. Holmes (2015),87,78,67,7.9,7.4,4.0,4.0,4.35,3.90,...,3.70,4.5,4.0,3.5,4.0,3.5,33,7367,1348,0.0
142,'71 (2015),97,82,83,7.5,7.2,3.5,3.5,4.85,4.10,...,3.60,5.0,4.0,4.0,4.0,3.5,60,24116,192,0.0
143,"Two Days, One Night (2014)",97,78,89,8.8,7.4,3.5,3.5,4.85,3.90,...,3.70,5.0,4.0,4.5,4.5,3.5,123,24345,118,0.0
144,Gett: The Trial of Viviane Amsalem (2015),100,81,90,7.3,7.8,3.5,3.5,5.00,4.05,...,3.90,5.0,4.0,4.5,3.5,4.0,19,1955,59,0.0
145,"Kumiko, The Treasure Hunter (2015)",87,63,68,6.4,6.7,3.5,3.5,4.35,3.15,...,3.35,4.5,3.0,3.5,3.0,3.5,19,5289,41,0.0

In [10]:
fandango.iloc[50,:]

FILM                          Pitch Perfect 2 (2015)
RottenTomatoes                                    67
RottenTomatoes_User                               68
Metacritic                                        63
Metacritic_User                                  5.7
IMDB                                             6.7
Fandango_Stars                                   4.5
Fandango_Ratingvalue                             4.2
RT_norm                                         3.35
RT_user_norm                                     3.4
Metacritic_norm                                 3.15
Metacritic_user_nom                             2.85
IMDB_norm                                       3.35
RT_norm_round                                    3.5
RT_user_norm_round                               3.5
Metacritic_norm_round                              3
Metacritic_user_norm_round                         3
IMDB_norm_round                                  3.5
Metacritic_user_vote_count                       192
IMDB_user_vote_count                           56333
Fandango_votes                                  4577
Fandango_Difference                              0.3
Name: 50, dtype: object

In [13]:
#ligne 45 et 90
fandango.iloc[[45,90],:]
#on utilise le [] pour extraire un ss ensemble de ligne

,FILM,RottenTomatoes,RottenTomatoes_User,Metacritic,Metacritic_User,IMDB,Fandango_Stars,Fandango_Ratingvalue,RT_norm,RT_user_norm,...,IMDB_norm,RT_norm_round,RT_user_norm_round,Metacritic_norm_round,Metacritic_user_norm_round,IMDB_norm_round,Metacritic_user_vote_count,IMDB_user_vote_count,Fandango_votes,Fandango_Difference
45,Tomorrowland (2015),50,53,60,6.4,6.6,4.0,3.7,2.5,2.65,...,3.30,2.5,2.5,3.0,3.0,3.5,262,42937,8077,0.3
90,The SpongeBob Movie: Sponge Out of Water (2015),78,55,62,6.5,6.1,3.5,3.3,3.9,2.75,...,3.05,4.0,3.0,3.0,3.5,3.0,196,26046,4493,0.2

In [15]:
first_last = fandango.iloc[[0,-1],:]
first_last

,FILM,RottenTomatoes,RottenTomatoes_User,Metacritic,Metacritic_User,IMDB,Fandango_Stars,Fandango_Ratingvalue,RT_norm,RT_user_norm,...,IMDB_norm,RT_norm_round,RT_user_norm_round,Metacritic_norm_round,Metacritic_user_norm_round,IMDB_norm_round,Metacritic_user_vote_count,IMDB_user_vote_count,Fandango_votes,Fandango_Difference
0,Avengers: Age of Ultron (2015),74,86,66,7.1,7.8,5.0,4.5,3.70,4.30,...,3.90,3.5,4.5,3.5,3.5,4.0,1330,271107,14846,0.5
145,"Kumiko, The Treasure Hunter (2015)",87,63,68,6.4,6.7,3.5,3.5,4.35,3.15,...,3.35,4.5,3.0,3.5,3.0,3.5,19,5289,41,0.0

### Utiliser des index personnalisés

In [16]:
#DataFrame.set_index(Series, inplace=True, drop=False)
#drop => Booléen. La valeur par défaut est “True” qui supprime la colonne à définir comme index
#inplace => Booléen. Si True, modifiez l’appelant DataFrame sur place
#Series => colonne ou liste de colonnes à définir comme index

In [17]:
#on souhaite conserver la colonne FILM
#On souhaite garder le DataFrame d'origine et en créer un nouveau que 
#nous assignerons à la variable fandango_films
fandango_films = fandango.set_index(fandango["FILM"],inplace=False, drop=False)

In [22]:
fandango_films.index

Index(['Avengers: Age of Ultron (2015)', 'Cinderella (2015)', 'Ant-Man (2015)',
       'Do You Believe? (2015)', 'Hot Tub Time Machine 2 (2015)',
       'The Water Diviner (2015)', 'Irrational Man (2015)', 'Top Five (2014)',
       'Shaun the Sheep Movie (2015)', 'Love & Mercy (2015)',
       ...
       'The Woman In Black 2 Angel of Death (2015)', 'Danny Collins (2015)',
       'Spare Parts (2015)', 'Serena (2015)', 'Inside Out (2015)',
       'Mr. Holmes (2015)', ''71 (2015)', 'Two Days, One Night (2014)',
       'Gett: The Trial of Viviane Amsalem (2015)',
       'Kumiko, The Treasure Hunter (2015)'],
      dtype='object', name='FILM', length=146)

### Sélectionner des valeurs depuis un index personnalisé

In [24]:
#Selection avec crochets ou methode loc[]
fandango_films["Mr. Holmes (2015)":"Two Days, One Night (2014)"]

,FILM,RottenTomatoes,RottenTomatoes_User,Metacritic,Metacritic_User,IMDB,Fandango_Stars,Fandango_Ratingvalue,RT_norm,RT_user_norm,...,IMDB_norm,RT_norm_round,RT_user_norm_round,Metacritic_norm_round,Metacritic_user_norm_round,IMDB_norm_round,Metacritic_user_vote_count,IMDB_user_vote_count,Fandango_votes,Fandango_Difference
FILM,,,,,,,,,,,,,,,,,,,,,
Mr. Holmes (2015),Mr. Holmes (2015),87,78,67,7.9,7.4,4.0,4.0,4.35,3.9,...,3.7,4.5,4.0,3.5,4.0,3.5,33,7367,1348,0.0
'71 (2015),'71 (2015),97,82,83,7.5,7.2,3.5,3.5,4.85,4.1,...,3.6,5.0,4.0,4.0,4.0,3.5,60,24116,192,0.0
"Two Days, One Night (2014)","Two Days, One Night (2014)",97,78,89,8.8,7.4,3.5,3.5,4.85,3.9,...,3.7,5.0,4.0,4.5,4.5,3.5,123,24345,118,0.0

In [25]:
fandango_films.loc["Mr. Holmes (2015)":"Two Days, One Night (2014)"]

,FILM,RottenTomatoes,RottenTomatoes_User,Metacritic,Metacritic_User,IMDB,Fandango_Stars,Fandango_Ratingvalue,RT_norm,RT_user_norm,...,IMDB_norm,RT_norm_round,RT_user_norm_round,Metacritic_norm_round,Metacritic_user_norm_round,IMDB_norm_round,Metacritic_user_vote_count,IMDB_user_vote_count,Fandango_votes,Fandango_Difference
FILM,,,,,,,,,,,,,,,,,,,,,
Mr. Holmes (2015),Mr. Holmes (2015),87,78,67,7.9,7.4,4.0,4.0,4.35,3.9,...,3.7,4.5,4.0,3.5,4.0,3.5,33,7367,1348,0.0
'71 (2015),'71 (2015),97,82,83,7.5,7.2,3.5,3.5,4.85,4.1,...,3.6,5.0,4.0,4.0,4.0,3.5,60,24116,192,0.0
"Two Days, One Night (2014)","Two Days, One Night (2014)",97,78,89,8.8,7.4,3.5,3.5,4.85,3.9,...,3.7,5.0,4.0,4.5,4.5,3.5,123,24345,118,0.0

In [27]:
#Film spécifique 
fandango_films.loc["Kumiko, The Treasure Hunter (2015)"]
#un objet series

FILM                          Kumiko, The Treasure Hunter (2015)
RottenTomatoes                                                87
RottenTomatoes_User                                           63
Metacritic                                                    68
Metacritic_User                                              6.4
IMDB                                                         6.7
Fandango_Stars                                               3.5
Fandango_Ratingvalue                                         3.5
RT_norm                                                     4.35
RT_user_norm                                                3.15
Metacritic_norm                                              3.4
Metacritic_user_nom                                          3.2
IMDB_norm                                                   3.35
RT_norm_round                                                4.5
RT_user_norm_round                                             3
Metacritic_norm_round                                        3.5
Metacritic_user_norm_round                                     3
IMDB_norm_round                                              3.5
Metacritic_user_vote_count                                    19
IMDB_user_vote_count                                        5289
Fandango_votes                                                41
Fandango_Difference                                            0
Name: Kumiko, The Treasure Hunter (2015), dtype: object

In [31]:
#Selection depuis une liste de films
movies = ["Kumiko, The Treasure Hunter (2015)",
          "Mr. Holmes (2015)",
          "Two Days, One Night (2014)"]
fandango_films.loc[movies]

,FILM,RottenTomatoes,RottenTomatoes_User,Metacritic,Metacritic_User,IMDB,Fandango_Stars,Fandango_Ratingvalue,RT_norm,RT_user_norm,...,IMDB_norm,RT_norm_round,RT_user_norm_round,Metacritic_norm_round,Metacritic_user_norm_round,IMDB_norm_round,Metacritic_user_vote_count,IMDB_user_vote_count,Fandango_votes,Fandango_Difference
FILM,,,,,,,,,,,,,,,,,,,,,
"Kumiko, The Treasure Hunter (2015)","Kumiko, The Treasure Hunter (2015)",87,63,68,6.4,6.7,3.5,3.5,4.35,3.15,...,3.35,4.5,3.0,3.5,3.0,3.5,19,5289,41,0.0
Mr. Holmes (2015),Mr. Holmes (2015),87,78,67,7.9,7.4,4.0,4.0,4.35,3.90,...,3.70,4.5,4.0,3.5,4.0,3.5,33,7367,1348,0.0
"Two Days, One Night (2014)","Two Days, One Night (2014)",97,78,89,8.8,7.4,3.5,3.5,4.85,3.90,...,3.70,5.0,4.0,4.5,4.5,3.5,123,24345,118,0.0

In [34]:
movies = ["Top Five (2014)",
          "Black Sea (2015)",
          "Taken 3 (2015)"]
fandango_films.loc[movies]

,FILM,RottenTomatoes,RottenTomatoes_User,Metacritic,Metacritic_User,IMDB,Fandango_Stars,Fandango_Ratingvalue,RT_norm,RT_user_norm,...,IMDB_norm,RT_norm_round,RT_user_norm_round,Metacritic_norm_round,Metacritic_user_norm_round,IMDB_norm_round,Metacritic_user_vote_count,IMDB_user_vote_count,Fandango_votes,Fandango_Difference
FILM,,,,,,,,,,,,,,,,,,,,,
Top Five (2014),Top Five (2014),86,64,81,6.8,6.5,4.0,3.5,4.30,3.2,...,3.25,4.5,3.0,4.0,3.5,3.5,124,16876,3223,0.5
Black Sea (2015),Black Sea (2015),82,60,62,6.6,6.4,4.0,3.5,4.10,3.0,...,3.20,4.0,3.0,3.0,3.5,3.0,37,16547,218,0.5
Taken 3 (2015),Taken 3 (2015),9,46,26,4.6,6.1,4.5,4.1,0.45,2.3,...,3.05,0.5,2.5,1.5,2.5,3.0,240,104235,6757,0.4

### Méthode Apply() sur les colonnes d'un DataFrame

In [35]:
#apply()
#datafrmae.apply(lambda x: x**2)

In [36]:
import numpy as np

In [38]:
# retourner les types de donnees en tant que series pour toutes les colonnes
types =fandango_films.dtypes
types

FILM                           object
RottenTomatoes                  int64
RottenTomatoes_User             int64
Metacritic                      int64
Metacritic_User               float64
IMDB                          float64
Fandango_Stars                float64
Fandango_Ratingvalue          float64
RT_norm                       float64
RT_user_norm                  float64
Metacritic_norm               float64
Metacritic_user_nom           float64
IMDB_norm                     float64
RT_norm_round                 float64
RT_user_norm_round            float64
Metacritic_norm_round         float64
Metacritic_user_norm_round    float64
IMDB_norm_round               float64
Metacritic_user_vote_count      int64
IMDB_user_vote_count            int64
Fandango_votes                  int64
Fandango_Difference           float64
dtype: object

In [52]:
#filtrer les nombres à virgules float64 
#et retourner le nom des colonnes
float_columns = types[types.values == 'float64'].index
float_columns

Index(['Metacritic_User', 'IMDB', 'Fandango_Stars', 'Fandango_Ratingvalue',
       'RT_norm', 'RT_user_norm', 'Metacritic_norm', 'Metacritic_user_nom',
       'IMDB_norm', 'RT_norm_round', 'RT_user_norm_round',
       'Metacritic_norm_round', 'Metacritic_user_norm_round',
       'IMDB_norm_round', 'Fandango_Difference'],
      dtype='object')

In [54]:
#utilisation des crochets pour filtrer 
#les colonnes de la condition float_columns
float_df = fandango_films[float_columns]
float_df

,Metacritic_User,IMDB,Fandango_Stars,Fandango_Ratingvalue,RT_norm,RT_user_norm,Metacritic_norm,Metacritic_user_nom,IMDB_norm,RT_norm_round,RT_user_norm_round,Metacritic_norm_round,Metacritic_user_norm_round,IMDB_norm_round,Fandango_Difference
FILM,,,,,,,,,,,,,,,
Avengers: Age of Ultron (2015),7.1,7.8,5.0,4.5,3.70,4.30,3.30,3.55,3.90,3.5,4.5,3.5,3.5,4.0,0.5
Cinderella (2015),7.5,7.1,5.0,4.5,4.25,4.00,3.35,3.75,3.55,4.5,4.0,3.5,4.0,3.5,0.5
Ant-Man (2015),8.1,7.8,5.0,4.5,4.00,4.50,3.20,4.05,3.90,4.0,4.5,3.0,4.0,4.0,0.5
Do You Believe? (2015),4.7,5.4,5.0,4.5,0.90,4.20,1.10,2.35,2.70,1.0,4.0,1.0,2.5,2.5,0.5
Hot Tub Time Machine 2 (2015),3.4,5.1,3.5,3.0,0.70,1.40,1.45,1.70,2.55,0.5,1.5,1.5,1.5,2.5,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Mr. Holmes (2015),7.9,7.4,4.0,4.0,4.35,3.90,3.35,3.95,3.70,4.5,4.0,3.5,4.0,3.5,0.0
'71 (2015),7.5,7.2,3.5,3.5,4.85,4.10,4.15,3.75,3.60,5.0,4.0,4.0,4.0,3.5,0.0
"Two Days, One Night (2014)",8.8,7.4,3.5,3.5,4.85,3.90,4.45,4.40,3.70,5.0,4.0,4.5,4.5,3.5,0.0
Gett: The Trial of Viviane Amsalem (2015),7.3,7.8,3.5,3.5,5.00,4.05,4.50,3.65,3.90,5.0,4.0,4.5,3.5,4.0,0.0
"Kumiko, The Treasure Hunter (2015)",6.4,6.7,3.5,3.5,4.35,3.15,3.40,3.20,3.35,4.5,3.0,3.5,3.0,3.5,0.0

In [57]:
#On calcule l'ecart-type de chaque colonne
deviations = float_df.apply(lambda x: np.std(x))
deviations

Metacritic_User               1.505529
IMDB                          0.955447
Fandango_Stars                0.538532
Fandango_Ratingvalue          0.501106
RT_norm                       1.503265
RT_user_norm                  0.997787
Metacritic_norm               0.972522
Metacritic_user_nom           0.752765
IMDB_norm                     0.477723
RT_norm_round                 1.509404
RT_user_norm_round            1.003559
Metacritic_norm_round         0.987561
Metacritic_user_norm_round    0.785412
IMDB_norm_round               0.501043
Fandango_Difference           0.152141
dtype: float64

Exercice

In [59]:
#On divise par deux :
exo_df = float_df.apply(lambda x : x/2)
exo_df

,Metacritic_User,IMDB,Fandango_Stars,Fandango_Ratingvalue,RT_norm,RT_user_norm,Metacritic_norm,Metacritic_user_nom,IMDB_norm,RT_norm_round,RT_user_norm_round,Metacritic_norm_round,Metacritic_user_norm_round,IMDB_norm_round,Fandango_Difference
FILM,,,,,,,,,,,,,,,
Avengers: Age of Ultron (2015),3.55,3.90,2.50,2.25,1.850,2.150,1.650,1.775,1.950,1.75,2.25,1.75,1.75,2.00,0.25
Cinderella (2015),3.75,3.55,2.50,2.25,2.125,2.000,1.675,1.875,1.775,2.25,2.00,1.75,2.00,1.75,0.25
Ant-Man (2015),4.05,3.90,2.50,2.25,2.000,2.250,1.600,2.025,1.950,2.00,2.25,1.50,2.00,2.00,0.25
Do You Believe? (2015),2.35,2.70,2.50,2.25,0.450,2.100,0.550,1.175,1.350,0.50,2.00,0.50,1.25,1.25,0.25
Hot Tub Time Machine 2 (2015),1.70,2.55,1.75,1.50,0.350,0.700,0.725,0.850,1.275,0.25,0.75,0.75,0.75,1.25,0.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Mr. Holmes (2015),3.95,3.70,2.00,2.00,2.175,1.950,1.675,1.975,1.850,2.25,2.00,1.75,2.00,1.75,0.00
'71 (2015),3.75,3.60,1.75,1.75,2.425,2.050,2.075,1.875,1.800,2.50,2.00,2.00,2.00,1.75,0.00
"Two Days, One Night (2014)",4.40,3.70,1.75,1.75,2.425,1.950,2.225,2.200,1.850,2.50,2.00,2.25,2.25,1.75,0.00
Gett: The Trial of Viviane Amsalem (2015),3.65,3.90,1.75,1.75,2.500,2.025,2.250,1.825,1.950,2.50,2.00,2.25,1.75,2.00,0.00
"Kumiko, The Treasure Hunter (2015)",3.20,3.35,1.75,1.75,2.175,1.575,1.700,1.600,1.675,2.25,1.50,1.75,1.50,1.75,0.00

### Méthode Apply() sur les lignes d'un DataFrame

In [61]:
#apply(function, axis =1 )

In [62]:
# on calcule l'ecart-type pour chaque film
rt_mt_user = float_df[['RT_user_norm','Metacritic_user_nom']]
rt_mt_user

                                           RT_user_norm  Metacritic_user_nom
FILM
Avengers: Age of Ultron (2015)                     4.30                 3.55
Cinderella (2015)                                  4.00                 3.75
Ant-Man (2015)                                     4.50                 4.05
Do You Believe? (2015)                             4.20                 2.35
Hot Tub Time Machine 2 (2015)                      1.40                 1.70
...                                                 ...                  ...
Mr. Holmes (2015)                                  3.90                 3.95
'71 (2015)                                         4.10                 3.75
Two Days, One Night (2014)                         3.90                 4.40
Gett: The Trial of Viviane Amsalem (2015)          4.05                 3.65
Kumiko, The Treasure Hunter (2015)                 3.15                 3.20

[146 rows x 2 columns]

In [63]:
rt_mt_user.apply(lambda x: np.std(x), axis=1)

FILM
Avengers: Age of Ultron (2015)               0.375
Cinderella (2015)                            0.125
Ant-Man (2015)                               0.225
Do You Believe? (2015)                       0.925
Hot Tub Time Machine 2 (2015)                0.150
                                             ...
Mr. Holmes (2015)                            0.025
'71 (2015)                                   0.175
Two Days, One Night (2014)                   0.250
Gett: The Trial of Viviane Amsalem (2015)    0.200
Kumiko, The Treasure Hunter (2015)           0.025
Length: 146, dtype: float64

In [64]:
rt_mt_user.apply(lambda x: np.mean(x), axis=1)

FILM
Avengers: Age of Ultron (2015)               3.925
Cinderella (2015)                            3.875
Ant-Man (2015)                               4.275
Do You Believe? (2015)                       3.275
Hot Tub Time Machine 2 (2015)                1.550
                                             ...
Mr. Holmes (2015)                            3.925
'71 (2015)                                   3.925
Two Days, One Night (2014)                   4.150
Gett: The Trial of Viviane Amsalem (2015)    3.850
Kumiko, The Treasure Hunter (2015)           3.175
Length: 146, dtype: float64